### ISSUE TITLE
Port to firefox / manifest@v3

### ISSUE THREAD

**Issue by ixrock** [ixrock/XTranslate#1]
**TODO**

- [x] manifest@v3 `content_scripts` not injected automatically (only after opening translator's window via toolbar icon), maybe extra  [chrome.scripting](https://developer.chrome.com/docs/extensions/reference/scripting/)-api required. 
Otherwise it works automatically only when user allows it manually per domain/site: **Right click at XTranslate** icon and Select **Extension can access site data: Always**
- [ ] manifest@v3 doesn't support `background.service_worker` (currently works via slow old-school `background.scripts`)
- [x] `chrome.runtime.sendMessage` and related methods doesn't support `Promise<Response>`
- [x] `chrome.tts` doesn't work, could be handled by #58 

**PREREQUISITES**

- Go to `about:config` system page
- Set `extensions.manifestV3.enabled` to `true`
- Set `xpinstall.signatures.required` to `false`
- You can now install MV3 extensions from `about:debugging` system browser page

**Availability in firefox extensions store:** ~~_(manifest@v2)_~~ `manifest@v3` since `v.4.2` _(mostly compatible)_
https://addons.mozilla.org/en-GB/firefox/addon/xtranslate-chrome/

**Comment by ixrock** [comment]
**Status**: 
won't be ported while it's not become good browser

**Problems:**
- Shadow-dom api not supported (only with enabled flag in `about:config`)
- Lacks of chrome extensions api: 
1) `chrome.storage.sync` - not supported
2) `chrome.runtime.onConnect(port => ...)` - where `port.sender.id` is id of window(?), instead of extension, but it has anyway (not-documented?) `port.sender.extensionId`
3) not possible to create custom-scrollbar styles with css-only

and some more minor problems...

**Comment by ixrock** [comment]
Reopened to investigate new changes since then..

**Comment by SergeyTverye** [comment]
> Reopened to investigate new changes since then..

Installed your extension in Firefox Developer today and everything seems to be working fine. It seems to me that you could upload the extension to the Firefox store. =)

**Comment by labi-le** [comment]
Is it relevant?

**Comment by ixrock** [comment]
What is relevant? Yes it's still in long non-priority todo-list if you want know ;)
If firefox-extensions store is fully compatible with chome-store apis (like edge-store), then (re)solution for the issue would be quite fast & trivial.

**Comment by ixrock** [comment]
Most of the features of manifest@v3 already supported in latest Firefox.
Therefore this probably long-awaited port becomes easily available! 

Addon link: https://addons.mozilla.org/en-GB/firefox/addon/xtranslate-chrome/ (will be updated soon to `v.4.2`)
Firefox active branch here: https://github.com/ixrock/XTranslate/tree/firefox

Thanks everyone for patience! :D

**Comment by ixrock** [comment]
Fully ported and available latest version for Firefox: https://addons.mozilla.org/en-US/firefox/addon/xtranslate-chrome/ (`v5.9.0`)
